[variables]
NIXPACKS_NODE_VERSION = "20"

[phases.setup]
nixPkgs = [
  "python3",      # requis pour node-gyp
  "gcc",          # compilateur
  "gnumake",      # make
  "ffmpeg",       # pour l’audio dans ton bot
  "nodejs_20"     # pour être sûr que le bon Node est là
]

[phases.build]
cmds = [
  "npm install"
]

[start]
cmd = "node index.js"
